package serv

import (
	"bytes"
	"github.com/golang/protobuf/proto"
	"github.com/sjmshsh/HopeIM"
	"github.com/sjmshsh/HopeIM/container"
	"github.com/sjmshsh/HopeIM/logger"
	"github.com/sjmshsh/HopeIM/wire"
	"github.com/sjmshsh/HopeIM/wire/pkt"
	"strings"
	"time"
)

var log = logger.WithFields(logger.Fields{
	"service": wire.SNChat,
	"pkg":     "serv",
})

type ServHanlder struct {
	r         *HopeIM.Router
	cache     HopeIM.SessionStorage
	dispather *ServerDispather
}

func NewServHandler(r *HopeIM.Router, cache HopeIM.SessionStorage) *ServHanlder {
	return &ServHanlder{
		r:         r,
		dispather: &ServerDispather{},
		cache:     cache,
	}
}

func (h *ServHanlder) Accept(conn HopeIM.Conn, timeout time.Duration) (string, error) {
	log.Infoln("enter")

	_ = conn.SetReadDeadline(time.Now().Add(timeout))
	frame, err := conn.ReadFrame()
	if err != nil {
		return "", err
	}

	var req pkt.InnerHandshakeReq
	_ = proto.Unmarshal(frame.GetPayload(), &req)
	log.Info("Accept -- ", req.ServiceId)

	return req.ServiceId, nil
}

func (h *ServHanlder) Receive(ag HopeIM.Agent, payload []byte) {
	buf := bytes.NewBuffer(payload)
	packet, err := pkt.MustReadLogicPkt(buf)
	if err != nil {
		log.Error(err)
		return
	}
	var session *pkt.Session
	if packet.Command == wire.CommandLoginSignIn {
		server, _ := packet.GetMeta(wire.MetaDestServer)
		session = &pkt.Session{
			ChannelId: packet.ChannelId,
			GateId:    server.(string),
			Tags:      []string{"AutoGenerated"},
		}
	} else {
		// TODO 优化点
		session, err = h.cache.Get(packet.ChannelId)
		if err == HopeIM.ErrSessionNil {
			_ = RespErr(ag, packet, pkt.Status_SessionNotFound)
			return
		} else if err != nil {
			_ = RespErr(ag, packet, pkt.Status_SystemException)
			return
		}
	}
	log.Debugf("recv a message from %s  %s", session, &packet.Header)
	err = h.r.Serve(packet, h.dispather, h.cache, session)
	if err != nil {
		log.Warn(err)
	}
}

func RespErr(ag HopeIM.Agent, p *pkt.LogicPkt, status pkt.Status) error {
	packet := pkt.NewFrom(&p.Header)
	packet.Status = status
	packet.Flag = pkt.Flag_Response

	return ag.Push(pkt.Marshal(packet))
}

type ServerDispather struct{}

func (d *ServerDispather) Push(gateway string, channels []string, p *pkt.LogicPkt) error {
	p.AddStringMeta(wire.MetaDestChannels, strings.Join(channels, ","))
	return container.Push(gateway, p)
}

// Disconnect default listener
func (h *ServHanlder) Disconnect(id string) error {
	logger.Warnf("close event of %s", id)
	return nil
}
